# Generated by Django 4.2.7 on 2023-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_rename_image_blog_thumnail_remove_blog_validity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
